import fs from 'node:fs/promises';
import { Workbook, SpreadsheetFile } from '@oai/artifact-tool';

const OUT='outputs/digital_asset_research_universe.xlsx';
const asOf='2026-08-22';
const cg=JSON.parse(await fs.readFile('work/coingecko_markets.json','utf8'));
const llama=JSON.parse(await fs.readFile('work/defillama_stablecoins.json','utf8')).peggedAssets;
const cgBySym=new Map(cg.map(x=>[x.symbol.toUpperCase(),x]));
const llBySym=new Map(llama.map(x=>[x.symbol.toUpperCase(),x]));

const cryptoSymbols=['BTC','ETH','BNB','XRP','SOL','TRX','HYPE','DOGE','ZEC','LINK','ADA','XMR','XLM','BCH','LTC','HBAR','SUI','AVAX','TON','TAO','UNI','AAVE','ARB','OP','POL'];
const stableSymbols=['USDT','USDC','USDS','DAI','USDE','USD1','USDG','PYUSD','RLUSD','USDD','GHO','FDUSD','TUSD','FRAX','USTC','PAXG'];
const growthSleeve=new Set(['HYPE','SUI','TAO','RLUSD','GHO','PYUSD','USDD']);

const meta={
BTC:['Bitcoin','L1','Money / settlement','PoW','none','https://bitcoin.org/en/bitcoin-core/features/validation'],ETH:['Ethereum','L1','Infrastructure + monetary','PoS','none','https://ethereum.org/developers/docs/intro-to-ether/'],BNB:['BNB','L1/ecosystem','Infrastructure + utility','PoS family','foundation/ecosystem','https://docs.bnbchain.org/'],XRP:['XRP','L1/payments','Settlement / payments','federated consensus','corporate/ecosystem','https://xrpl.org/docs/concepts/tokens/xrp'],SOL:['Solana','L1','Infrastructure','PoS family','foundation','https://solana.com/docs/core/fees'],TRX:['TRON','L1/payments','Infrastructure + settlement','DPoS','foundation','https://developers.tron.network/docs/resource-model'],HYPE:['Hyperliquid','L1/DeFi','Infrastructure + exchange','PoS family','foundation','https://hyperliquid.gitbook.io/hyperliquid-docs/'],DOGE:['Dogecoin','L1','Monetary / payments','PoW','none','https://dogecoin.com/dogepedia/'],ZEC:['Zcash','L1/privacy','Monetary / privacy','PoW','foundation','https://zcash.readthedocs.io/'],LINK:['Chainlink','Oracle','Oracle/service infrastructure','service staking','foundation','https://docs.chain.link/'],ADA:['Cardano','L1','Infrastructure','PoS','foundation','https://docs.cardano.org/about-cardano/learn/consensus-explained/'],XMR:['Monero','L1/privacy','Monetary / privacy','PoW','none','https://www.getmonero.org/resources/about/'],XLM:['Stellar','L1/payments','Settlement / payments','federated consensus','foundation','https://developers.stellar.org/docs/learn/fundamentals/stellar-data-structures/assets'],BCH:['Bitcoin Cash','L1','Monetary / payments','PoW','none','https://documentation.cash/'],LTC:['Litecoin','L1','Monetary / payments','PoW','foundation','https://litecoin.org/'],HBAR:['Hedera','L1','Infrastructure','hashgraph PoS','council','https://docs.hedera.com/hedera/core-concepts/hbar'],SUI:['Sui','L1','Infrastructure','PoS','foundation','https://docs.sui.io/concepts/tokenomics'],AVAX:['Avalanche','L1','Infrastructure','PoS','foundation','https://build.avax.network/docs/quick-start/avalanche-consensus'],TON:['Toncoin','L1','Infrastructure + payments','PoS','foundation','https://docs.ton.org/v3/documentation/'],TAO:['Bittensor','AI network','Service/incentive network','PoS family','foundation','https://docs.learnbittensor.org/'],UNI:['Uniswap','DeFi','Exchange governance','NA','DAO','https://docs.uniswap.org/concepts/governance/overview'],AAVE:['Aave','DeFi','Lending governance/security','NA','DAO','https://aave.com/docs/aave-v3/overview'],ARB:['Arbitrum','L2','Scaling governance','rollup','DAO/foundation','https://docs.arbitrum.foundation/concepts/arbitrumdao-governance'],OP:['Optimism','L2','Scaling governance','rollup','foundation/collective','https://docs.optimism.io/governance/'],POL:['Polygon Ecosystem Token','Infrastructure','Security / ecosystem','PoS','foundation','https://docs.polygon.technology/pos/concepts/tokens/pol/']};

const va={
BTC:[1,0,0,0,1,1,0,0,0,0],ETH:[1,1,1,1,0,1,0,1,1,0],BNB:[0,1,1,1,0,1,0,1,1,1],XRP:[1,1,0,1,1,0,0,1,1,0],SOL:[0,1,1,1,0,1,0,1,1,0],TRX:[1,1,1,1,0,1,1,1,1,1],HYPE:[0,1,1,1,0,0,1,1,1,1],DOGE:[1,1,0,0,0,0,0,0,0,0],ZEC:[1,1,0,0,1,0,0,0,0,0],LINK:[0,0,1,0,0,0,0,1,1,1],ADA:[0,1,1,0,1,1,1,1,1,0],XMR:[1,1,0,0,0,0,0,0,0,0],XLM:[1,1,0,1,1,0,1,1,1,0],BCH:[1,1,0,0,1,0,0,0,0,0],LTC:[1,1,0,0,1,0,0,0,0,0],HBAR:[0,1,1,0,1,0,1,1,1,1],SUI:[0,1,1,0,1,1,1,1,1,1],AVAX:[0,1,1,1,1,1,1,1,1,1],TON:[0,1,1,0,0,1,1,1,1,1],TAO:[0,1,1,0,1,0,1,1,1,1],UNI:[0,0,0,0,0,0,1,0,0,1],AAVE:[0,0,1,0,0,0,1,1,1,1],ARB:[0,0,0,0,0,0,1,0,0,1],OP:[0,0,0,0,0,0,1,1,0,1],POL:[0,1,1,0,0,0,1,1,1,1]};

const st={
USDT:['Tether','S1','USD','fiat reserves','R3','issuer direct restricted',0,'https://tether.to/en/transparency/'],USDC:['USD Coin','S1','USD','cash, short Treasuries and repo/MMF structure','R2','issuer direct broad',0,'https://www.circle.com/transparency'],USDS:['Sky Dollar','S2','USD','protocol collateral','R1','protocol/open',0,'https://developers.sky.money/'],DAI:['Dai','S2','USD','protocol collateral','R1','protocol/open',0,'https://docs.makerdao.com/'],USDE:['Ethena USDe','S3','USD','crypto/stables plus derivatives hedges','R3','approved primary process',0,'https://docs.ethena.fi/'],USD1:['World Liberty Financial USD','S1','USD','fiat reserve structure','R3','restricted/issuer process',0,'https://www.worldlibertyfinancial.com/'],USDG:['Global Dollar','S1','USD','fiat reserve structure','R2','issuer direct',0,'https://www.globaldollar.com/'],PYUSD:['PayPal USD','S1','USD','fiat deposits, Treasuries, cash equivalents','R2','issuer/intermediary',0,'https://www.paxos.com/pyusd'],RLUSD:['Ripple USD','S1','USD','cash and cash equivalents / Treasuries','R3','issuer/approved counterparties',0,'https://ripple.com/solutions/stablecoin/'],USDD:['USDD','S2','USD','crypto collateral / protocol mechanisms','R1','protocol mechanisms',0,'https://usdd.io/'],GHO:['GHO','S2','USD','Aave collateral/facilitator architecture','R1','protocol/open',0,'https://aave.com/docs/primitives/gho'],FDUSD:['First Digital USD','S1','USD','fiat reserve assets','R3','issuer direct restricted',0,'https://firstdigitallabs.com/'],TUSD:['TrueUSD','S1','USD','fiat reserve assets','R3','issuer direct restricted',0,'https://tusd.io/'],FRAX:['Frax','S2','USD','protocol collateral / monetary mechanisms','R1','protocol/open',0,'https://docs.frax.finance/'],USTC:['TerraClassicUSD','S4','USD','historical reflexive algorithmic mechanism','R0','none/current legacy asset',0,'https://classic-docs.terra.money/'],PAXG:['PAX Gold','S5','gold','allocated physical gold','R3','issuer direct restricted',0,'https://www.paxos.com/paxgold']};

const wb=Workbook.create();
const sheets={}; for(const n of ['README','Universe','asset_master','economic_design','stablecoin_design','Codebook','Sources']) sheets[n]=wb.worksheets.add(n);
wb.comments.setSelf({displayName:'User'});
const navy='#173A5E', teal='#167D7F', pale='#EAF2F6', gray='#5D6B75', white='#FFFFFF', gold='#C9972F', green='#DFF2E1', red='#F9E2E2';
function title(sh,text,sub,cols){sh.showGridLines=false; sh.getRange(`A1:${cols}1`).merge(); sh.getRange('A1').values=[[text]]; sh.getRange('A1').format={fill:navy,font:{bold:true,color:white,size:18},rowHeight:32,verticalAlignment:'center'}; sh.getRange(`A2:${cols}2`).merge(); sh.getRange('A2').values=[[sub]]; sh.getRange('A2').format={font:{italic:true,color:gray,size:10},rowHeight:25,wrapText:true};}
function header(sh,range){sh.getRange(range).format={fill:teal,font:{bold:true,color:white},wrapText:true,verticalAlignment:'center',borders:{preset:'inside',style:'thin',color:'#D7E2E8'}};}
function body(sh,range){sh.getRange(range).format={font:{size:9,color:'#17242E'},wrapText:true,verticalAlignment:'center',borders:{insideHorizontal:{style:'thin',color:'#DDE5E9'}}};}
function widths(sh,map){for(const [col,w] of Object.entries(map)) sh.getRange(`${col}:${col}`).format.columnWidth=w;}

// README
title(sheets.README,'Digital Asset Research Universe','Pilot sample, classification workbook, and audit trail • snapshot '+asOf,'H');
sheets.README.getRange('A4:B11').values=[['Field','Definition'],['Purpose','Freeze the Phase 1 pilot universe and populate the three research schemas.'],['Selection logic','Market dominance first; liquidity/data accessibility second; a limited growth sleeve third.'],['Crypto rule','Include market-leading non-stables, then add economically distinct liquid assets and high-growth candidates with usable history.'],['Stablecoin rule','Cover most USD-stablecoin capitalization plus structurally distinct, fast-growing, and failed controls.'],['Snapshot','CoinGecko markets + global data and DeFiLlama stablecoins, retrieved 2026-08-22.'],['Important','Selection and design codes are research classifications, not investment recommendations or legal conclusions.'],['Maintenance','Update market fields by dated snapshot; update design fields only through effective-dated revisions and source evidence.']]; header(sheets.README,'A4:B4'); body(sheets.README,'A5:B11'); widths(sheets.README,{A:22,B:92}); sheets.README.freezePanes.freezeRows(4);
sheets.README.getRange('D4:H8').values=[['Workbook status','Value'],['Crypto assets selected',cryptoSymbols.length],['Stable-value assets selected',stableSymbols.length],['Growth-sleeve observations',[...growthSleeve].length],['Current classifications needing source review','See review_status / confidence fields']]; header(sheets.README,'D4:H4'); body(sheets.README,'D5:H8');

// Universe
title(sheets.Universe,'Universe Selection','Market-cap, volume, growth, economic coverage, and inclusion rationale','N');
const uh=['asset_id','symbol','name','universe','market_cap_rank','market_cap_usd','volume_24h_usd','volume_to_mcap','change_30d','change_1y','selection_tier','high_growth_story','inclusion_rationale','snapshot_source'];
const urows=[];
for(const sym of cryptoSymbols){const x=cgBySym.get(sym); if(!x) continue; const m=meta[sym]; const tier=growthSleeve.has(sym)?'Growth sleeve':(x.market_cap_rank<=20?'Market core':'Economic coverage'); urows.push([`crypto_${sym.toLowerCase()}`,sym,m[0],'crypto',x.market_cap_rank,x.market_cap,x.total_volume,null,x.price_change_percentage_30d_in_currency/100,x.price_change_percentage_1y_in_currency==null?null:x.price_change_percentage_1y_in_currency/100,tier,growthSleeve.has(sym),tier==='Market core'?'Large, liquid market representative':tier==='Growth sleeve'?'High recent growth / expanding economic relevance with accessible data':'Adds valuation-mechanism or sector coverage','https://api.coingecko.com/api/v3/coins/markets']);}
for(const sym of stableSymbols){const s=st[sym]; const l=llBySym.get(sym); const c=l?.circulating?.peggedUSD||0, prev=l?.circulatingPrevMonth?.peggedUSD||0; const x=cgBySym.get(sym); const tier=sym==='USTC'?'Failure control':growthSleeve.has(sym)?'Growth sleeve':c>=1e9?'Market core':'Structural coverage'; urows.push([`stable_${sym.toLowerCase()}`,sym,s[0],'stablecoin',x?.market_cap_rank||null,c||x?.market_cap||null,x?.total_volume||null,null,prev?c/prev-1:null,null,tier,growthSleeve.has(sym),tier==='Failure control'?'Required failed/reflexive negative control':tier==='Market core'?'Large stablecoin market representative':tier==='Growth sleeve'?'Rapid supply/adoption growth with economically relevant scale':'Adds backing/redemption mechanism coverage','https://stablecoins.llama.fi/stablecoins?includePrices=true']);}
sheets.Universe.getRange(`A4:N${3+urows.length}`).values=[uh,...urows];
for(let r=5;r<=4+urows.length;r++) sheets.Universe.getRange(`H${r}`).formulas=[[`=IFERROR(G${r}/F${r},0)`]];
header(sheets.Universe,'A4:N4'); body(sheets.Universe,`A5:N${4+urows.length}`); sheets.Universe.tables.add(`A4:N${4+urows.length}`,true,'UniverseTable'); sheets.Universe.freezePanes.freezeRows(4); sheets.Universe.freezePanes.freezeColumns(2);
sheets.Universe.getRange(`F5:H${4+urows.length}`).format.numberFormat='#,##0'; sheets.Universe.getRange(`I5:J${4+urows.length}`).format.numberFormat='0.0%';
sheets.Universe.getRange(`K5:K${4+urows.length}`).conditionalFormats.add('containsText',{text:'Growth',format:{fill:green,font:{color:'#176B2C',bold:true}}});
sheets.Universe.getRange(`K5:K${4+urows.length}`).conditionalFormats.add('containsText',{text:'Failure',format:{fill:red,font:{color:'#8A1C1C',bold:true}}});
widths(sheets.Universe,{A:20,B:10,C:22,D:13,E:12,F:17,G:17,H:14,I:12,J:12,K:18,L:14,M:42,N:48});

// asset_master
title(sheets.asset_master,'asset_master','Stable identifiers and core economic/technical attributes','O');
const ah=['asset_id','symbol','asset_name','asset_family','economic_function_primary','economic_function_secondary','layer','consensus','issuer_type','launch_date','inactive_date','status','selection_tier','source_url','review_status'];
const ar=[];
for(const sym of cryptoSymbols){const m=meta[sym],u=urows.find(r=>r[1]===sym); ar.push([`crypto_${sym.toLowerCase()}`,sym,m[0],m[1],m[2],'',m[1],m[3],m[4],null,null,'active',u?.[10],m[5],'pilot coded']);}
for(const sym of stableSymbols){const s=st[sym],u=urows.find(r=>r[1]===sym); ar.push([`stable_${sym.toLowerCase()}`,sym,s[0],'stablecoin','Money / settlement',s[1],s[1],'NA',sym==='USTC'?'protocol':'issuer/protocol',null,null,sym==='USTC'?'failed/legacy':'active',u?.[10],s[7],'pilot coded']);}
sheets.asset_master.getRange(`A4:O${3+ar.length}`).values=[ah,...ar]; header(sheets.asset_master,'A4:O4'); body(sheets.asset_master,`A5:O${4+ar.length}`); sheets.asset_master.tables.add(`A4:O${4+ar.length}`,true,'AssetMasterTable'); sheets.asset_master.freezePanes.freezeRows(4); sheets.asset_master.freezePanes.freezeColumns(2); widths(sheets.asset_master,{A:20,B:9,C:23,D:18,E:30,F:25,G:14,H:18,I:20,J:13,K:13,L:15,M:18,N:50,O:16});

// economic_design
title(sheets.economic_design,'economic_design','Formal binary value-accrual and rights/claims coding • pilot codes require second-coder review','Y');
const eh=['asset_id','valid_from','valid_to','va_monetary','va_gas','va_stake','va_burn','va_scarcity','va_collateral','va_gov','va_protocol','va_utility','va_incentive','va_breadth_count','claim_redemption','claim_collateral','claim_cashflow','claim_governance','claim_none','supply_model','evidence_url','evidence_date','coder','confidence','review_status'];
const er=[];
for(const sym of cryptoSymbols){const m=meta[sym],v=va[sym]; const claims=[0,0,0,(v[6]||0),v[6]?0:1]; er.push([`crypto_${sym.toLowerCase()}`,asOf,null,...v,null,...claims,v[4]?'bounded/capped or constrained':'managed/issuance',m[5],asOf,'primary agent',sym==='BTC'||sym==='ETH'?'high':'medium','needs second coder']);}
for(let i=0;i<er.length;i++){const row=5+i; er[i][13]=null;}
sheets.economic_design.getRange(`A4:Y${3+er.length}`).values=[eh,...er];
for(let r=5;r<=4+er.length;r++) sheets.economic_design.getRange(`N${r}`).formulas=[[`=SUM(D${r}:M${r})`]];
header(sheets.economic_design,'A4:Y4'); body(sheets.economic_design,`A5:Y${4+er.length}`); sheets.economic_design.tables.add(`A4:Y${4+er.length}`,true,'EconomicDesignTable'); sheets.economic_design.freezePanes.freezeRows(4); sheets.economic_design.freezePanes.freezeColumns(3); sheets.economic_design.getRange(`D5:S${4+er.length}`).format.numberFormat='0'; sheets.economic_design.getRange(`D5:M${4+er.length}`).conditionalFormats.add('cellIs',{operator:'equal',formula:1,format:{fill:green,font:{color:'#176B2C',bold:true}}}); widths(sheets.economic_design,{A:20,B:13,C:13,D:12,E:9,F:10,G:10,H:12,I:12,J:9,K:12,L:10,M:12,N:12,O:13,P:13,Q:13,R:13,S:11,T:24,U:50,V:13,W:16,X:12,Y:20});

// stablecoin_design
title(sheets.stablecoin_design,'stablecoin_design','Backing, redemption, growth, and preliminary risk inputs','V');
const sh=['asset_id','symbol','valid_from','valid_to','peg_asset','backing_class','reserve_type','centralized_issuer','redemption_code','redemption_description','direct_redemption','holder_yield_base_token','month_supply_growth','market_cap_usd','reserve_quality_score','redemption_friction_score','transparency_score','terms_url','reserve_report_url','evidence_date','confidence','review_status'];
const sr=[];
for(const sym of stableSymbols){const s=st[sym],l=llBySym.get(sym),c=l?.circulating?.peggedUSD||cgBySym.get(sym)?.market_cap||null,prev=l?.circulatingPrevMonth?.peggedUSD||0; const direct=['R1','R2','R3'].includes(s[4]); sr.push([`stable_${sym.toLowerCase()}`,sym,asOf,null,s[2],s[1],s[3],s[1]==='S1'||s[1]==='S5',s[4],s[5],direct,s[6],prev?c/prev-1:null,c,null,null,null,s[7],s[7],asOf,'medium','score inputs pending document review']);}
sheets.stablecoin_design.getRange(`A4:V${3+sr.length}`).values=[sh,...sr]; header(sheets.stablecoin_design,'A4:V4'); body(sheets.stablecoin_design,`A5:V${4+sr.length}`); sheets.stablecoin_design.tables.add(`A4:V${4+sr.length}`,true,'StablecoinDesignTable'); sheets.stablecoin_design.freezePanes.freezeRows(4); sheets.stablecoin_design.freezePanes.freezeColumns(2); sheets.stablecoin_design.getRange(`M5:M${4+sr.length}`).format.numberFormat='0.0%'; sheets.stablecoin_design.getRange(`N5:N${4+sr.length}`).format.numberFormat='#,##0'; widths(sheets.stablecoin_design,{A:20,B:9,C:13,D:13,E:11,F:13,G:42,H:15,I:12,J:28,K:15,L:17,M:16,N:17,O:16,P:18,Q:16,R:48,S:48,T:13,U:12,V:30});

// Codebook
title(sheets.Codebook,'Classification Codebook','Operational rules used by economic_design and stablecoin_design','D');
const codes=[['code','set_to_1_when','exclusions','primary_review_evidence'],['VA_MONETARY','Material money, settlement, reserve/store-of-value use; meet at least two behavioral tests.','Marketing or mere transferability alone.','usage, integrations, holdings, monetary policy'],['VA_GAS','Protocol requires token for ordinary transaction/computation/storage fees.','Optional discounts or automatic conversion only.','protocol fee specification'],['VA_STAKE','Token is locked/delegated or economically at risk to secure network/service.','Passive yield or liquidity mining alone.','staking/slashing rules'],['VA_BURN','Live rules-based mechanism irreversibly destroys tokens.','Promised or discretionary future burn.','contract/protocol plus observed burn'],['VA_SCARCITY','Credible hard cap/deterministic terminal bound with exceptional-change threshold.','Routine governance override or nominal max with weak credibility.','consensus/supply specification'],['VA_COLLATERAL','Collateral TVL ≥1% of market cap or ≥$100m for ≥90 days.','LP pairing or staking alone.','protocol collateral listings + TVL'],['VA_GOV','Live voting/proposal/veto/treasury control.','Informal signaling only.','governance contracts/rules'],['VA_PROTOCOL','Live route from protocol revenue/surplus to holders.','Future fee-switch promise; record option separately.','distribution/buyback/burn mechanism'],['VA_UTILITY','Required for identifiable non-generic service beyond transfer.','Governance or tradability alone.','service payment/access rule'],['VA_INCENTIVE','Systematic subsidy for liquidity, usage, development, or participation.','Consensus rewards unless separable program.','emissions/incentive program'],['R0','No functioning redemption.','','terms/contract'],['R1','Open protocol redemption.','','contract'],['R2','Broad eligible issuer redemption.','','issuer terms'],['R3','Restricted issuer redemption.','','eligibility/minimum/fee'],['R4','Intermediated exit for ordinary holders.','','issuer terms + market structure'],['R5','Material gate, suspension, delay, or in-kind right.','','terms and event history']];
sheets.Codebook.getRange(`A4:D${3+codes.length}`).values=codes; header(sheets.Codebook,'A4:D4'); body(sheets.Codebook,`A5:D${3+codes.length}`); sheets.Codebook.freezePanes.freezeRows(4); widths(sheets.Codebook,{A:18,B:62,C:55,D:38});

// Sources
title(sheets.Sources,'Source Registry','Primary design sources and current market snapshots','E');
const src=[['source_id','source_name','url','retrieved_at','use'],['cg_markets','CoinGecko Markets API','https://api.coingecko.com/api/v3/coins/markets',asOf,'market cap, volume, rank, 30d/1y performance'],['cg_global','CoinGecko Global API','https://api.coingecko.com/api/v3/global',asOf,'total market cap and dominance'],['llama_stables','DeFiLlama Stablecoins API','https://stablecoins.llama.fi/stablecoins?includePrices=true',asOf,'stablecoin circulating supply and monthly change'],['bis_stables','BIS Working Paper 1164','https://www.bis.org/publ/work1164.htm',asOf,'reserve transparency/quality and run-risk framework'],['cpmi_stables','CPMI stablecoin considerations','https://www.bis.org/cpmi/publ/d220.pdf',asOf,'reserve, segregation, redemption framework'],['defillama_defs','DeFiLlama Data Definitions','https://defillama.com/data-definitions',asOf,'fees/revenue/TVL measurement']];
sheets.Sources.getRange(`A4:E${3+src.length}`).values=src; header(sheets.Sources,'A4:E4'); body(sheets.Sources,`A5:E${3+src.length}`); widths(sheets.Sources,{A:20,B:35,C:70,D:15,E:48});

// Audit-friendly validation
sheets.asset_master.getRange(`L5:L${4+ar.length}`).dataValidation={rule:{type:'list',values:['active','inactive','failed/legacy','migrated']}};
sheets.economic_design.getRange(`X5:X${4+er.length}`).dataValidation={rule:{type:'list',values:['low','medium','high']}};
sheets.stablecoin_design.getRange(`U5:U${4+sr.length}`).dataValidation={rule:{type:'list',values:['low','medium','high']}};
await fs.mkdir('outputs',{recursive:true});
const file=await SpreadsheetFile.exportXlsx(wb); await file.save(OUT);
for(const n of ['README','Universe','asset_master','economic_design','stablecoin_design','Codebook','Sources']){
 const preview=await wb.render({sheetName:n,autoCrop:'all',scale:0.8,format:'png'}); await fs.writeFile(`work/preview_${n}.png`,new Uint8Array(await preview.arrayBuffer()));
}
const check=await wb.inspect({kind:'table',range:'Universe!A4:N12',include:'values,formulas',tableMaxRows:12,tableMaxCols:14,maxChars:5000}); console.log(check.ndjson);
const errors=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A',options:{useRegex:true,maxResults:100},summary:'formula error scan'}); console.log(errors.ndjson);
console.log(OUT);
