from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

PHASES = {
    "00_foundation": ("Foundation", "Shared market, price and activity series that more than one phase consumes."),
    "01_classification": ("Phase 1 — Economic classification", "Evidence, mechanism states, review reconciliation and the ten-function taxonomy."),
    "02_valuation": ("Phase 2 — Valuation tests", "H1 usage, H2 fee-and-capture, H3 supply, H8 breadth, and the mechanism event studies."),
    "03_risk": ("Phase 3 — Risk and market structure", "Return panel, factor baseline, and the P1_H6 function-versus-risk test."),
    "04_stablecoin_deferred": ("Phase 4 — Stablecoin risk (deferred)", "H5-H7 work, preserved and not an active gate."),
}
SKIP = {"__init__", "run_stages", "data_map"}


def modules(repo: Path) -> dict[str, str]:
    return {p.stem: p.read_text(encoding="utf-8") for p in sorted((repo / "src/pipeline").glob("*.py")) if p.stem not in SKIP}


def configs(repo: Path) -> dict[str, str]:
    return {p.name: p.read_text(encoding="utf-8") for p in sorted((repo / "config").glob("*.json"))}


def classify(name: str, source: str) -> str:
    """A module writes a file if the name appears near a write verb, otherwise it reads it."""
    for match in re.finditer(re.escape(name), source):
        window = source[max(0, match.start() - 220): match.end() + 120]
        if re.search(r"write_rows|write_csv|write_text|DictWriter|\.open\(\s*[\"']w|write_audit|out\s*/|output\s*/", window):
            return "writes"
    return "reads"


def build(repo: Path) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    mods, cfgs = modules(repo), configs(repo)
    rows: list[dict[str, Any]] = []
    for phase in PHASES:
        directory = repo / "data/processed" / phase
        if not directory.is_dir():
            continue
        for path in sorted(directory.iterdir()):
            if not path.is_file():
                continue
            stem = path.stem
            writers, readers = [], []
            for module, src in mods.items():
                if path.name in src:
                    (writers if classify(path.name, src) == "writes" else readers).append(module)
                elif re.search(r'f?"\{?' + re.escape(stem), src) or f'"{stem}"' in src:
                    writers.append(module)          # built from a dynamic stem
            writers, readers = sorted(set(writers)), sorted(set(readers))
            specs = sorted(c for c, src in cfgs.items() if path.name in src or f'"{stem}"' in src)
            rows.append({
                "phase": phase, "file": path.name,
                "kind": "table" if path.suffix == ".csv" else "summary",
                "bytes": path.stat().st_size,
                "written_by": writers, "read_by": readers, "named_in_config": specs,
                "orphan": not writers and not specs,
            })
    summary = {
        "status": "data_map_complete",
        "files": len(rows),
        "by_phase": {p: sum(r["phase"] == p for r in rows) for p in PHASES},
        "orphans": [r["file"] for r in rows if r["orphan"]],
        "terminal_outputs": [r["file"] for r in rows if r["written_by"] and not r["read_by"] and not r["named_in_config"]],
    }
    return rows, summary


def render(rows: list[dict[str, Any]], summary: dict[str, Any]) -> str:
    out = ["# Data map", "",
           "Generated by `python -m src.pipeline.data_map --repo .`. Every processed file, which phase it belongs to, which module writes it and which modules read it. Do not edit by hand.", "",
           f"**{summary['files']} processed files.** " + " · ".join(f"{PHASES[p][0]}: {n}" for p, n in summary["by_phase"].items() if n), ""]
    if summary["orphans"]:
        out += ["> **Orphans** (no module writes these; they are stale unless a collector produces them): " + ", ".join(f"`{o}`" for o in summary["orphans"]), ""]
    out += ["## How data flows", "", "```mermaid", "flowchart LR",
            '  RAW["data/raw/<br/>immutable snapshots"] --> F["00_foundation<br/>shared series"]',
            '  F --> C["01_classification<br/>Phase 1 evidence"]',
            "  C --> V[\"02_valuation<br/>H1 H2 H3 H8\"]", "  C --> R[\"03_risk<br/>return and risk\"]",
            "  F --> V", "  F --> R", '  F -.-> S["04_stablecoin_deferred<br/>parked"]',
            "  classDef active fill:#E0A33E,stroke:#132238,color:#132238;",
            "  classDef idle fill:#eceff3,stroke:#8A97A6,color:#40566E;",
            "  class C active; class RAW,F,V,R idle; class S idle;", "```", ""]
    for phase, (title, blurb) in PHASES.items():
        group = [r for r in rows if r["phase"] == phase]
        if not group:
            continue
        out += [f"## {title}", "", blurb, "", f"`data/processed/{phase}/`", "",
                "| File | Written by | Read by |", "|---|---|---|"]
        for r in group:
            w = ", ".join(f"`{m}`" for m in r["written_by"]) or "—"
            rd = ", ".join(f"`{m}`" for m in r["read_by"])
            if r["named_in_config"]:
                rd = (rd + " · " if rd else "") + "via " + ", ".join(f"`{c}`" for c in r["named_in_config"])
            rd = rd or "terminal output"
            out.append(f"| `{r['file']}` | {w} | {rd} |")
        out.append("")
    return "\n".join(out)


def run(repo: Path) -> dict[str, Any]:
    rows, summary = build(repo)
    (repo / "DATA_MAP.md").write_text(render(rows, summary), encoding="utf-8")
    out = repo / "data/processed/00_foundation"
    out.mkdir(parents=True, exist_ok=True)
    (out / "data_map.json").write_text(json.dumps({"summary": summary, "files": rows}, indent=2) + "\n", encoding="utf-8")
    return summary


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate the data lineage map")
    parser.add_argument("--repo", type=Path, default=Path.cwd())
    print(json.dumps(run(parser.parse_args().repo.resolve()), indent=2))
